### ISSUE TITLE
Hardcode paths

### ISSUE THREAD

**Issue by jacksonpradolima** [icse20/RT-CI#2]
For instance: https://github.com/icse20/RT-CI/blob/84b67f728caa0625b0e317baa9bd83fd9c0ae5d6/code/TestSelection/push.sh#L8

**Comment by antonioguerrierounina** [comment]
Yes, you are right. 
You should insert the local path of the application to test (the applications are not in the repo).
We will update the script according to your comment.

**Comment by lujiayun** [comment]
Hello, in the push.sh file, should I execute "git log" from the cloned commons-math repository and then go to my own repository to create a local branch and push to which remote repository?
And in the statement done < "$1" ，is "$1" replaced with "log800.txt"?
I execute  the "CD local/path/to/application_under_test #.. /.. After "/commons-math", and then execute "git push" will connect to its remote repository, causing the connection to fail. What's the problem, please? 
Look forward to your answer, thank you very much!
